name: mypetfit_app
description: "Pet health assessment and product recommendation app"
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  go_router: ^17.2.2
  google_fonts: ^8.0.2
  smooth_page_indicator: ^2.0.1
  shared_preferences: ^2.3.5
  lottie: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo/mypetfit_logo.png
    - assets/animations/dog_walking.json
